[package]
name = "home-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.7.2"
actix-files = "0.6"
actix-ratelimit = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.3.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4"] }
dotenv = "0.15"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite", "chrono"] }
mime = "0.3"
rustls = "0.23.25"
rustls-pemfile = "2.2.0"
async-trait = "0.1"
